insert into games (id, title, short, long, cat, cover, color, best, plays) values
  ('bloque-buster', 'BLOQUE BUSTER', 'Rebota la pelota y destruye muros de neón.', 'Pilota una nave-paleta y rebota un núcleo de plasma para pulverizar muros de bloques cromáticos. Cada nivel reorganiza la grilla en patrones imposibles. ¿Hasta dónde llegará tu racha?', 'ARCADE', 'cover-bricks', 'cyan', 28450, '12.4K'),
  ('caida', 'CAÍDA', 'Encaja las piezas antes de que el techo te aplaste.', 'Piezas geométricas descienden desde la oscuridad. Rótalas, encástralas y limpia líneas para sobrevivir. La velocidad aumenta sin piedad cada 10 líneas.', 'PUZZLE', 'cover-tetro', 'magenta', 184220, '31.8K'),
  ('serpentina', 'SERPENTINA', 'Crece sin morder tu propia cola.', 'Una serpiente de luz recorre la grilla buscando núcleos magenta. Cada bocado la alarga y la hace más veloz. Un movimiento en falso y se devora a sí misma.', 'ARCADE', 'cover-snake', 'green', 7820, '9.1K'),
  ('gloton', 'GLOTÓN', 'Devora puntos y escapa de los fantasmas.', 'Un círculo glotón patrulla un laberinto coleccionando puntos luminosos. Cuatro espectros lo persiguen, pero cada cierto tiempo aparece una píldora que invierte los papeles.', 'ARCADE', 'cover-glot', 'yellow', 96400, '27.2K'),
  ('invasores', 'INVASORES', 'Defiende el planeta de filas alienígenas.', 'Olas de pixeles hostiles descienden formación tras formación. Mueve tu cañón en horizontal y abre fuego con precisión, antes de que toquen la superficie.', 'SHOOTER', 'cover-invaders', 'green', 54190, '18.0K'),
  ('asteroids', 'ASTEROIDS', 'Sobrevive al campo de rocas en gravedad cero.', 'Pilota tu nave triangular entre esquirlas de roca a la deriva. Rota, propulsa y dispara para partir cada asteroide en fragmentos más pequeños, recoge el power-up de disparo triple y aguanta tanto como puedas antes de que las rocas te alcancen.', 'SHOOTER', 'cover-asteroids', 'yellow', 0, '0'),
  ('rocas', 'ROCAS', 'Pulveriza asteroides en gravedad cero.', 'Tu nave triangular flota en vacío absoluto. Dispara y rota para dividir rocas en fragmentos cada vez más pequeños. Cuidado con los OVNIs en el horizonte.', 'SHOOTER', 'cover-rocas', 'yellow', 41200, '15.6K'),
  ('ranaria', 'RANARIA', 'Cruza la autopista de pixeles.', 'Salta entre carriles de coches a toda velocidad y troncos a la deriva en el río. Llega a los nenúfares antes de que se acabe el tiempo.', 'ARCADE', 'cover-rana', 'green', 18900, '6.4K'),
  ('duelo-pixel', 'DUELO PIXEL', 'Dos paletas. Una pelota. Reflejos máximos.', 'El duelo más puro: dos paletas verticales se enfrentan por rebotar una pelota luminosa. Modo solitario contra la CPU o partida local a dos jugadores.', 'VERSUS', 'cover-duelo', 'cyan', 24, '4.2K'),
  ('tetris', 'TETRIS', 'Encaja piezas cayendo antes de que te desborden.', 'Piezas geométricas de siete formas —más una tuerca metálica escondida— caen sin pausa. Rota, encaja y limpia líneas completas antes de que la pila alcance el techo. La velocidad sube cada 10 líneas.', 'PUZZLE', 'cover-tetris', 'cyan', 0, '0'),
  ('arkanoid', 'ARKANOID', 'Destruye 5 muros de bloques antes de perder tus 3 vidas.', 'Controla una paleta con mouse o teclado y rebota una bola de energía contra 5 formaciones de bloques cada vez más veloces. Cada bloque destruido estalla en una animación de partículas y suma puntos. Pierde una vida si la bola cae al vacío; pierde las 3 y todo termina.', 'ARCADE', 'cover-arkanoid', 'magenta', 0, '0'),
  ('snake', 'SNAKE', 'Devora frutas de neón y crece sin chocar contigo mismo.', 'Guía una serpiente de píxeles por una grilla infinita, devorando frutas brillantes que la hacen crecer y acelerar. Un choque contra tu propia cola o el borde del campo termina la partida al instante.', 'ARCADE', 'cover-snake-real', 'green', 0, '0');
